<?php use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header') ?>
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form action=" " method="post">
                    <h3 class="text-center mb-4">Login</h3>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-user-shield"></i></span>
                        </div>
                        <input type="text" class="form-control" name="username" placeholder="Username" aria-label="Username">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-lock"></i></span>
                        </div>
                        <input type="password" class="form-control" name="password" placeholder="Password" aria-label="Password">
                    </div>
                    <input type="submit" class="btn btn-primary" style="float:right" value="Entrar"></input>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
