<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>

<div class="container mt-3">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form action=" " method="post">
                <br>
                <h3 class="text-center mb-4">Registo</h3>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                    </div>
                    <input type="text" class="form-control" name="name" placeholder="Nome">

                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                    </div>
                    <input type="email" class="form-control" name="email" placeholder="Email">

                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                    </div>
                    <input type="date" class="form-control" name="nascdate" placeholder="Data de Nacimento">

                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-user-shield"></i></span>
                    </div>
                    <input type="text" class="form-control" name="username" placeholder="Username">

                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-lock"></i></span>
                    </div>
                    <input type="password" class="form-control" name="password" placeholder="Password">

                </div>
                <center> <input type="submit" class="btn btn-primary" value="Criar Conta"></input></center>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>